services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: btg
      POSTGRES_PASSWORD: btg123
      POSTGRES_DB: BTG
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg-data:
  